export const actionTypes = {
  FETCH_MEMBERS_COMPLETED: 'FETCH_MEMBERS_COMPLETED',
  FETCH_MEMBER_BY_ID_COMPLETED: 'FETCH_MEMBER_BY_ID_COMPLETED',
  UPDATE_MEMBER_FIELD: 'UPDATE_MEMBER_FIELD',
  SAVE_MEMBER: 'SAVE_MEMBER',
  FETCH_NOTES_COMPLETED: 'FETCH_NOTES_COMPLETED',
  SAVE_NOTE: 'SAVE_NOTE',
  UPDATE_NOTE_FIELD: 'UPDATE_NOTE_FIELD',
};
