export const actionTypes = {
  FETCH_NOTES_COMPLETED: 'FETCH_NOTES_COMPLETED',
  SAVE_NOTE: 'SAVE_NOTE',
  UPDATE_NOTE_FIELD: 'UPDATE_NOTE_FIELD',
  FETCH_NOTES_BY_ID_COMPLETED: 'FETCH_NOTES_BY_ID_COMPLETED',
  UPDATE_CONTENT_NOTE_FIELD: 'UPDATE_CONTENT_NOTE_FIELD',
  DELETE_NOTES_BY_ID: 'DELETE_NOTES_BY_ID',
  UPDATE_NOTE_BY_ID_COMPLETED: 'UPDATE_NOTE_BY_ID_COMPLETED',
};
